import type { AppState } from '../types';

export const DEFAULT_STATE: AppState = {
  mode: null,
  sessionState: 'ModeSelect',
  previousSessionState: 'GSL',
  theme: 'dark',
  defaultMajorityType: 'simple',
  delegates: [],
  topic: '',
  gsl: {
    isOpen: false,
    speakers: [],
    currentIndex: 0,
    speakingTimeSecs: 90,
    timerRunning: false,
    timerRemaining: 90,
  },
  modCaucus: {
    topic: '',
    totalTimeSecs: 600,
    speakingTimeSecs: 60,
    totalRemaining: 600,
    speakerRemaining: 60,
    speakers: [],
    currentSpeakerIndex: 0,
    speakerRunning: false,
    started: false,
  },
  unmod: {
    totalTimeSecs: 300,
    remaining: 300,
    running: false,
    previousState: 'GSL',
  },
  roundRobin: {
    participants: [],
    currentIndex: 0,
    speakingTimeSecs: 60,
    timerRemaining: 60,
    timerRunning: false,
    started: false,
    complete: false,
  },
  motions: [],
  votingRecords: [],
  workingPapers: [],
};
